{"links": {"self": {"href": "data/repositories/labscript_suite/labscript_devices/pullrequests/75/comments/108209754.json"}, "html": {"href": "#!/labscript_suite/labscript_devices/pull-requests/75/_/diff#comment-108209754"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 75, "links": {"self": {"href": "data/repositories/labscript_suite/labscript_devices/pullrequests/75.json"}, "html": {"href": "#!/labscript_suite/labscript_devices/pull-requests/75"}}, "title": "RfBlasterPy3 bugfix"}, "content": {"raw": "I have just updated G.99 to Py3 \\(and don\u2019t have any RFBlasters in here at the moment anyway\\), and G.96 is offline ready to be rebuilt when parts arrive, so should get a fresh Py3 update before things get going again in there too. I don\u2019t think that we need to worry about Py2.7 compatibility for RFBlasters anymore.", "markup": "markdown", "html": "<p>I have just updated G.99 to Py3 (and don\u2019t have any RFBlasters in here at the moment anyway), and G.96 is offline ready to be rebuilt when parts arrive, so should get a fresh Py3 update before things get going again in there too. I don\u2019t think that we need to worry about Py2.7 compatibility for RFBlasters anymore.</p>", "type": "rendered"}, "created_on": "2019-07-05T06:35:04.183630+00:00", "user": {"display_name": "Shaun Johnstone", "uuid": "{652df738-313d-472c-b7b5-a3f8f98a3322}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D"}, "html": {"href": "https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/38984f1761fc67ce892911496abee619d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSJ-3.png"}}, "nickname": "shjohnst", "type": "user", "account_id": "557058:1b9a15fb-8e4f-407e-b7b9-567c5e1fa1b4"}, "updated_on": "2019-07-05T06:35:04.193200+00:00", "type": "pullrequest_comment", "id": 108209754}