{"links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/pullrequests/28/comments/57376475.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/pull-requests/28/_/diff#comment-57376475"}}, "parent": {"id": 57365587, "links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/pullrequests/28/comments/57365587.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/pull-requests/28/_/diff#comment-57365587"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 28, "links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/pullrequests/28.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/pull-requests/28"}}, "title": "Python3"}, "content": {"raw": "Dtype fieldnames must be the native string type if we are working with lists. Dictionaries however work fine receiving either unicode or byte strings under python 2 and 3. I'm trying to get around this fact with this hack any other ideas?\n\n[https://github.com/numpy/numpy/issues/2407](https://github.com/numpy/numpy/issues/2407)\n\n\u200c\n\nIt is really useful when porting devices and labscript.py", "markup": "markdown", "html": "<p>Dtype fieldnames must be the native string type if we are working with lists. Dictionaries however work fine receiving either unicode or byte strings under python 2 and 3. I'm trying to get around this fact with this hack any other ideas?</p>\n<p><a data-is-external-link=\"true\" href=\"https://github.com/numpy/numpy/issues/2407\" rel=\"nofollow\">https://github.com/numpy/numpy/issues/2407</a></p>\n<p>\u200c</p>\n<p>It is really useful when porting devices and labscript.py</p>", "type": "rendered"}, "created_on": "2018-02-27T07:18:40.492567+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": "2018-02-27T07:25:16.140119+00:00", "type": "pullrequest_comment", "id": 57376475}