{"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/38/comments/44464394.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/38#comment-44464394"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/38.json"}}, "type": "issue", "id": 38, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "Front Panel settings set to default on load when connection table is modified under Python 3"}, "content": {"raw": "Does adding ```name = _ensure_str(name)``` to the top of ```find_by_name``` in labscript_utils/connections.py solve the bug for you? It seems that name is sometimes passed as a numpy string.", "markup": "markdown", "html": "<p>Does adding <code>name = _ensure_str(name)</code> to the top of <code>find_by_name</code> in labscript_utils/connections.py solve the bug for you? It seems that name is sometimes passed as a numpy string.</p>", "type": "rendered"}, "created_on": "2018-04-03T20:21:44.263183+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": "2018-04-03T20:22:01.452834+00:00", "type": "issue_comment", "id": 44464394}