{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26/comments/39122090.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/26#comment-39122090"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26.json"}}, "type": "issue", "id": 26, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "queue_data is stored as a QtObject under pyqt4"}, "content": {"raw": "the problem was caused by  [line 157 in queue.py](#!/labscript_suite/blacs/src/6603a0783157ccc862d1ff28f0f78af4ff1fe194/queue.py?at=default&fileviewer=file-view-default#queue.py-157). But changing this now won't help so as I said I'll write some try catch clauses in main.py where saved data is used.", "markup": "markdown", "html": "<p>the problem was caused by  <a data-is-external-link=\"true\" href=\"#!/labscript_suite/blacs/src/6603a0783157ccc862d1ff28f0f78af4ff1fe194/queue.py?at=default&amp;fileviewer=file-view-default#queue.py-157\" rel=\"nofollow\">line 157 in queue.py</a>. But changing this now won't help so as I said I'll write some try catch clauses in main.py where saved data is used.</p>", "type": "rendered"}, "created_on": "2017-08-16T14:13:51.130276+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": null, "type": "issue_comment", "id": 39122090}, {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26/comments/39122683.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/26#comment-39122683"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26.json"}}, "type": "issue", "id": 26, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "queue_data is stored as a QtObject under pyqt4"}, "content": {"raw": "So I created a pull request to fix the issue but we should check if we need to fix the cause in a later update as well. \n\nThe fix is tested on the machine that had the problem and works.\n\nUpdate: checked and under qtutils2/QtAPIv2 queue_data  is stored as string so no need for further fixing", "markup": "markdown", "html": "<p>So I created a pull request to fix the issue but we should check if we need to fix the cause in a later update as well. </p>\n<p>The fix is tested on the machine that had the problem and works.</p>\n<p>Update: checked and under qtutils2/QtAPIv2 queue_data  is stored as string so no need for further fixing</p>", "type": "rendered"}, "created_on": "2017-08-16T14:40:22.175549+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": "2017-08-16T14:54:24.312222+00:00", "type": "issue_comment", "id": 39122683}, {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26/comments/39127142.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/26#comment-39127142"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26.json"}}, "type": "issue", "id": 26, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "queue_data is stored as a QtObject under pyqt4"}, "content": {"raw": "Fixed by pull request #16", "markup": "markdown", "html": "<p>Fixed by <a href=\"#!/labscript_suite/blacs/pull-requests/16/quick-fix-for-config-errors-after-qtutils\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #16</a></p>", "type": "rendered"}, "created_on": "2017-08-16T18:28:35.676580+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 39127142}, {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26/comments/39132371.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/26#comment-39132371"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/26.json"}}, "type": "issue", "id": 26, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "queue_data is stored as a QtObject under pyqt4"}, "content": {"raw": "When we release the next version of BLACS we should make an announcement on the mailing list and make sure to mention that the contents of the Queue will be lost then (since the fix is just to throw everything in the queue away)", "markup": "markdown", "html": "<p>When we release the next version of BLACS we should make an announcement on the mailing list and make sure to mention that the contents of the Queue will be lost then (since the fix is just to throw everything in the queue away)</p>", "type": "rendered"}, "created_on": "2017-08-17T01:45:21.450535+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 39132371}], "page": 1, "size": 4}