{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "links": {"attachments": {"href": "data/repositories/labscript_suite/blacs/issues/48/attachments_page=1.json"}, "self": {"href": "data/repositories/labscript_suite/blacs/issues/48.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/blacs/issues/48/watch"}, "comments": {"href": "data/repositories/labscript_suite/blacs/issues/48/comments_page=1.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/48/devices-with-broken-code-break-blacs-even"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/blacs/issues/48/vote"}}, "reporter": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "title": "Devices with broken code break BLACS (even though we supposedly fixed this)", "component": null, "votes": 0, "watches": 1, "content": {"raw": "The code to gracefully handle device tabs that raise exceptions (when they are instantiated) is broken. It modifies the dictionary we are iterating over, which then raises it's own exception (at least under Python 3.6).\r\n\r\nWe should store the devices to remove in a list, and then remove them after we have attempted to initialise each device tab.\r\n\r\nSee lines 277 and 291 [here](#!/labscript_suite/blacs/src/f6faf14e9f6285e6cdecfc76260343ba3dd56f3f/__main__.py?at=default&fileviewer=file-view-default#__main__.py-277)", "markup": "markdown", "html": "<p>The code to gracefully handle device tabs that raise exceptions (when they are instantiated) is broken. It modifies the dictionary we are iterating over, which then raises it's own exception (at least under Python 3.6).</p>\n<p>We should store the devices to remove in a list, and then remove them after we have attempted to initialise each device tab.</p>\n<p>See lines 277 and 291 <a data-is-external-link=\"true\" href=\"#!/labscript_suite/blacs/src/f6faf14e9f6285e6cdecfc76260343ba3dd56f3f/__main__.py?at=default&amp;fileviewer=file-view-default#__main__.py-277\" rel=\"nofollow\">here</a></p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-09-20T04:45:29.964089+00:00", "milestone": null, "updated_on": "2018-10-01T20:11:30.488156+00:00", "type": "issue", "id": 48}