{"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/25/comments/39024507.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/25#comment-39024507"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "Error when starting BLACS from console"}, "content": {"raw": "Thanks for looking into it. Didn't think it was much of a problem until now nor did I know I was starting all my labscript apps 'wrong'. Btw what does work is doing  ```python __main__.py``` and ```python FULLPATH/blacs/__main__.py``` where as ```python blacs/__main__.py``` doesn't work. Why exactly shouldn't I run things directly from the directory?", "markup": "markdown", "html": "<p>Thanks for looking into it. Didn't think it was much of a problem until now nor did I know I was starting all my labscript apps 'wrong'. Btw what does work is doing  <code>python __main__.py</code> and <code>python FULLPATH/blacs/__main__.py</code> where as <code>python blacs/__main__.py</code> doesn't work. Why exactly shouldn't I run things directly from the directory?</p>", "type": "rendered"}, "created_on": "2017-08-10T23:33:19.992972+00:00", "user": {"display_name": "Jan Werkmann", "uuid": "{44c4905c-2b90-4045-a5f1-652b8e228626}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D"}, "html": {"href": "https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5/07e5095a-4741-4dc0-a462-9c7d455f961d/128"}}, "nickname": "PhyNerd", "type": "user", "account_id": "557058:a70cc9cf-684e-4849-a61a-9ade4d7218b5"}, "updated_on": "2017-08-10T23:40:48.305382+00:00", "type": "issue_comment", "id": 39024507}