{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729507.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729507"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "The `QColor` issue is not related to this. Somewhere between version 4.11.1 and 4.11.4, they dropped support for automatically calling functions that were passed in. `QColor(lambda: Qt.Red)` works on 4.11.1 and not on 4.11.4. I probably didn't mean to be passing in a function, but it used to work anyway!\n\nI think the issue with the strings here is because `abspath` is implemented differently on windows and linux, so Shaun didn't see the error (it doesn't show up on windows). He's implemented your fix with `str` for now and will make a new pull request shortly. We should probably turn on API v2, but that requires more debugging and effort to make sure that PySide still works properly too (assuming we don't just drop PySide support...)", "markup": "markdown", "html": "<p>The <code>QColor</code> issue is not related to this. Somewhere between version 4.11.1 and 4.11.4, they dropped support for automatically calling functions that were passed in. <code>QColor(lambda: Qt.Red)</code> works on 4.11.1 and not on 4.11.4. I probably didn't mean to be passing in a function, but it used to work anyway!</p>\n<p>I think the issue with the strings here is because <code>abspath</code> is implemented differently on windows and linux, so Shaun didn't see the error (it doesn't show up on windows). He's implemented your fix with <code>str</code> for now and will make a new pull request shortly. We should probably turn on API v2, but that requires more debugging and effort to make sure that PySide still works properly too (assuming we don't just drop PySide support...)</p>", "type": "rendered"}, "created_on": "2017-06-21T00:21:33.750394+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 37729507}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729519.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729519"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "Also, FYI pyqtgraph is specifically imported **after** the PyQt4/PySide is imported (there is a comment to this effect in the code)", "markup": "markdown", "html": "<p>Also, FYI pyqtgraph is specifically imported <strong>after</strong> the PyQt4/PySide is imported (there is a comment to this effect in the code)</p>", "type": "rendered"}, "created_on": "2017-06-21T00:22:53.299126+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 37729519}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729536.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729536"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "Ah, but the version check on pyqtgraph (which import pyqtgraph) happens prior.", "markup": "markdown", "html": "<p>Ah, but the version check on pyqtgraph (which import pyqtgraph) happens prior.</p>", "type": "rendered"}, "created_on": "2017-06-21T00:24:57.646903+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 37729536}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729547.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729547"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "Oh, well that's a bug then!", "markup": "markdown", "html": "<p>Oh, well that's a bug then!</p>", "type": "rendered"}, "created_on": "2017-06-21T00:26:23.971227+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "updated_on": null, "type": "issue_comment", "id": 37729547}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729577.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729577"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "As for the fix: Thanks! Anyone going to do any major rejigging of GUI code should decide whether it's worth making the switch to API 2 before or after, but other than that this is entirely sufficient for the moment.\n\nWe'll see if Pyside is up to scratch with the latest Python 3 and Qt 5 by the time the other programs are being ported, if it is then we don't have to choose to drop it.", "markup": "markdown", "html": "<p>As for the fix: Thanks! Anyone going to do any major rejigging of GUI code should decide whether it's worth making the switch to API 2 before or after, but other than that this is entirely sufficient for the moment.</p>\n<p>We'll see if Pyside is up to scratch with the latest Python 3 and Qt 5 by the time the other programs are being ported, if it is then we don't have to choose to drop it.</p>", "type": "rendered"}, "created_on": "2017-06-21T00:29:57.855542+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 37729577}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37729602.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37729602"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "Somewhat relatedly, had a bug recently where pandas 0.20.1 would import PyQt4 and set the API to version 1. Lyse of course was not happy about this. Pandas has since fixed it to make those imports optional. Didn't seem to happen on my system though, despite using the same version of pandas, but if anyone sees that, there's your explanation.", "markup": "markdown", "html": "<p>Somewhat relatedly, had a bug recently where pandas 0.20.1 would import PyQt4 and set the API to version 1. Lyse of course was not happy about this. Pandas has since fixed it to make those imports optional. Didn't seem to happen on my system though, despite using the same version of pandas, but if anyone sees that, there's your explanation.</p>", "type": "rendered"}, "created_on": "2017-06-21T00:32:45.079820+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 37729602}, {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10/comments/37855617.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/10#comment-37855617"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/10.json"}}, "type": "issue", "id": 10, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "Filepath issue, possible Qt API issues"}, "content": {"raw": "Fixed in pull request #8", "markup": "markdown", "html": "<p>Fixed in <a href=\"#!/labscript_suite/runviewer/pull-requests/8/fix-for-issue-10-filepath-issue-possible\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #8</a></p>", "type": "rendered"}, "created_on": "2017-06-27T06:06:21.407088+00:00", "user": {"display_name": "Shaun Johnstone", "uuid": "{652df738-313d-472c-b7b5-a3f8f98a3322}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D"}, "html": {"href": "https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/38984f1761fc67ce892911496abee619d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSJ-3.png"}}, "nickname": "shjohnst", "type": "user", "account_id": "557058:1b9a15fb-8e4f-407e-b7b9-567c5e1fa1b4"}, "updated_on": null, "type": "issue_comment", "id": 37855617}], "page": 1, "size": 7}