{"links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/issues/17/comments/44877259.json"}, "html": {"href": "#!/labscript_suite/labscript_utils/issues/17#comment-44877259"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils/issues/17.json"}}, "type": "issue", "id": 17, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/labscript_utils.json"}, "html": {"href": "#!/labscript_suite/labscript_utils"}, "avatar": {"href": "data/bytebucket.org/ravatar/{68347210-fb1e-4b58-86c0-bd2c04396e63}ts=249922"}}, "type": "repository", "name": "labscript_utils", "full_name": "labscript_suite/labscript_utils", "uuid": "{68347210-fb1e-4b58-86c0-bd2c04396e63}"}, "title": "RuntimeError: dictionary changed size during iteration"}, "content": {"raw": "Should be fixed by pull request #44", "markup": "markdown", "html": "<p>Should be fixed by <a href=\"#!/labscript_suite/labscript_utils/pull-requests/44/fix-issue-17\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #44</a></p>", "type": "rendered"}, "created_on": "2018-04-23T01:43:24.548455+00:00", "user": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "updated_on": null, "type": "issue_comment", "id": 44877259}