{"priority": "critical", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/installer.json"}, "html": {"href": "#!/labscript_suite/installer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{65cd9685-3e8c-4275-9b89-1a7873b341d0}ts=python"}}, "type": "repository", "name": "installer", "full_name": "labscript_suite/installer", "uuid": "{65cd9685-3e8c-4275-9b89-1a7873b341d0}"}, "links": {"attachments": {"href": "data/repositories/labscript_suite/installer/issues/29/attachments_page=1.json"}, "self": {"href": "data/repositories/labscript_suite/installer/issues/29.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/installer/issues/29/watch"}, "comments": {"href": "data/repositories/labscript_suite/installer/issues/29/comments_page=1.json"}, "html": {"href": "#!/labscript_suite/installer/issues/29/importlib_metadata-package-should-be-added"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/installer/issues/29/vote"}}, "reporter": {"display_name": "Philip Starkey", "uuid": "{0147401a-13ed-4e39-a0d0-63108c18738b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0147401a-13ed-4e39-a0d0-63108c18738b%7D"}, "html": {"href": "https://bitbucket.org/%7B0147401a-13ed-4e39-a0d0-63108c18738b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/fa0698c306b3470c00717c146b5296e9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "philipstarkey", "type": "user", "account_id": "557058:2f99420c-1dbd-4837-952c-82c421b8fbdd"}, "title": "importlib_metadata package should be added to the required dependencies", "component": null, "votes": 0, "watches": 2, "content": {"raw": "I just did a fresh install under Python 3.7 and ran into an error because I had not installed the `importlib_metadata` package from PyPi. This should be added as a required dependency so the installer doesn\u2019t crash half-way through.", "markup": "markdown", "html": "<p>I just did a fresh install under Python 3.7 and ran into an error because I had not installed the <code>importlib_metadata</code> package from PyPi. This should be added as a required dependency so the installer doesn\u2019t crash half-way through.</p>", "type": "rendered"}, "assignee": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-08-06T13:22:21.935031+00:00", "milestone": null, "updated_on": "2019-08-12T16:11:17.308071+00:00", "type": "issue", "id": 29}