{"rendered": {"message": {"raw": "Fix issue #56 for Python 2. Python 3 fix will have to wait for a pull request\nsubmitted to h5py", "markup": "markdown", "html": "<p>Fix issue #56 for Python 2. Python 3 fix will have to wait for a pull request<br />\nsubmitted to h5py</p>", "type": "rendered"}}, "hash": "2c49ec2297698e60b271f926533b8cd9e38239b3", "repository": {"links": {"self": {"href": "data/repositories/dihm/runmanager.json"}, "html": {"href": "#!/dihm/runmanager"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b4eae553-2dc8-4579-b697-a57e879bcb02}ts=python"}}, "type": "repository", "name": "runmanager", "full_name": "dihm/runmanager", "uuid": "{b4eae553-2dc8-4579-b697-a57e879bcb02}"}, "links": {"self": {"href": "data/repositories/dihm/runmanager/commit/2c49ec2297698e60b271f926533b8cd9e38239b3.json"}, "comments": {"href": "data/repositories/dihm/runmanager/commit/2c49ec2297698e60b271f926533b8cd9e38239b3/comments_page=1.json"}, "patch": {"href": "https://api.bitbucket.org/2.0/repositories/dihm/runmanager/patch/2c49ec2297698e60b271f926533b8cd9e38239b3"}, "html": {"href": "#!/dihm/runmanager/commits/2c49ec2297698e60b271f926533b8cd9e38239b3"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/dihm/runmanager/diff/2c49ec2297698e60b271f926533b8cd9e38239b3"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/dihm/runmanager/commit/2c49ec2297698e60b271f926533b8cd9e38239b3/approve"}, "statuses": {"href": "data/repositories/dihm/runmanager/commit/2c49ec2297698e60b271f926533b8cd9e38239b3/statuses_page=1.json"}}, "author": {"raw": "chrisjbillington", "type": "author"}, "summary": {"raw": "Fix issue #56 for Python 2. Python 3 fix will have to wait for a pull request\nsubmitted to h5py", "markup": "markdown", "html": "<p>Fix issue #56 for Python 2. Python 3 fix will have to wait for a pull request<br />\nsubmitted to h5py</p>", "type": "rendered"}, "participants": [], "parents": [{"hash": "96ee800fb6beefc0d92ead87bccd6daebddd5431", "type": "commit", "links": {"self": {"href": "data/repositories/dihm/runmanager/commit/96ee800fb6beefc0d92ead87bccd6daebddd5431.json"}, "html": {"href": "#!/dihm/runmanager/commits/96ee800fb6beefc0d92ead87bccd6daebddd5431"}}}], "date": "2018-05-10T05:36:16+00:00", "message": "Fix issue #56 for Python 2. Python 3 fix will have to wait for a pull request\nsubmitted to h5py", "type": "commit", "git_hash": "1b6ea60b5ad6225c8cede96caecfd8693adb1117", "tags": null, "branches": "bugfix"}