{"rendered": {"message": {"raw": "Hotfix for issue #67 - sequence index file not found causes crash on python 2", "markup": "markdown", "html": "<p>Hotfix for issue #67 - sequence index file not found causes crash on python 2</p>", "type": "rendered"}}, "hash": "3e0aa6e835249e67617b34f7fcae6f851e8f25d5", "repository": {"links": {"self": {"href": "data/repositories/dsbarker/runmanager.json"}, "html": {"href": "#!/dsbarker/runmanager"}, "avatar": {"href": "data/bytebucket.org/ravatar/{734e289d-d45d-4993-a92d-c7b7216a361e}ts=python"}}, "type": "repository", "name": "runmanager", "full_name": "dsbarker/runmanager", "uuid": "{734e289d-d45d-4993-a92d-c7b7216a361e}"}, "links": {"self": {"href": "data/repositories/dsbarker/runmanager/commit/3e0aa6e835249e67617b34f7fcae6f851e8f25d5.json"}, "comments": {"href": "data/repositories/dsbarker/runmanager/commit/3e0aa6e835249e67617b34f7fcae6f851e8f25d5/comments_page=1.json"}, "patch": {"href": "https://api.bitbucket.org/2.0/repositories/dsbarker/runmanager/patch/3e0aa6e835249e67617b34f7fcae6f851e8f25d5"}, "html": {"href": "#!/dsbarker/runmanager/commits/3e0aa6e835249e67617b34f7fcae6f851e8f25d5"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/dsbarker/runmanager/diff/3e0aa6e835249e67617b34f7fcae6f851e8f25d5"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/dsbarker/runmanager/commit/3e0aa6e835249e67617b34f7fcae6f851e8f25d5/approve"}, "statuses": {"href": "data/repositories/dsbarker/runmanager/commit/3e0aa6e835249e67617b34f7fcae6f851e8f25d5/statuses_page=1.json"}}, "author": {"raw": "chrisjbillington", "type": "author"}, "summary": {"raw": "Hotfix for issue #67 - sequence index file not found causes crash on python 2", "markup": "markdown", "html": "<p>Hotfix for issue #67 - sequence index file not found causes crash on python 2</p>", "type": "rendered"}, "participants": [], "parents": [{"hash": "f598b77f5b16d31330dbfd189d5be2358461aaad", "type": "commit", "links": {"self": {"href": "data/repositories/dsbarker/runmanager/commit/f598b77f5b16d31330dbfd189d5be2358461aaad.json"}, "html": {"href": "#!/dsbarker/runmanager/commits/f598b77f5b16d31330dbfd189d5be2358461aaad"}}}], "date": "2019-04-18T16:28:10+00:00", "message": "Hotfix for issue #67 - sequence index file not found causes crash on python 2", "type": "commit", "git_hash": "b2ca5d9ed415c65a82261761a447989efa586a61", "tags": null, "branches": "default"}