{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runmanager.json"}, "html": {"href": "#!/labscript_suite/runmanager"}, "avatar": {"href": "data/bytebucket.org/ravatar/{9b4f21e6-54b0-41ea-8f01-db1919f2f790}ts=249918"}}, "type": "repository", "name": "runmanager", "full_name": "labscript_suite/runmanager", "uuid": "{9b4f21e6-54b0-41ea-8f01-db1919f2f790}"}, "links": {"attachments": {"href": "data/repositories/labscript_suite/runmanager/issues/29/attachments_page=1.json"}, "self": {"href": "data/repositories/labscript_suite/runmanager/issues/29.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runmanager/issues/29/watch"}, "comments": {"href": "data/repositories/labscript_suite/runmanager/issues/29/comments_page=1.json"}, "html": {"href": "#!/labscript_suite/runmanager/issues/29/standard-output-and-standard-error-of"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runmanager/issues/29/vote"}}, "reporter": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "title": "Standard output and standard error of subprocess out of sync.", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Child process returns nonsense ordering of standard out and standard error, as if the two are being written to from separate threads, even when they're not.\r\n\r\nThis requires a fix in zprocess, and then runmanager will have to change to use it.\r\n\r\nAlso this looks terrible, howcome nobody reported this as a big before? :p", "markup": "markdown", "html": "<p>Child process returns nonsense ordering of standard out and standard error, as if the two are being written to from separate threads, even when they're not.</p>\n<p>This requires a fix in zprocess, and then runmanager will have to change to use it.</p>\n<p>Also this looks terrible, howcome nobody reported this as a big before? :p</p>", "type": "rendered"}, "assignee": {"display_name": "Chris Billington", "uuid": "{e363c5a9-5075-4656-afb5-88bd6a6dceeb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D"}, "html": {"href": "https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/9238baf7300c41c0e7294db922899e6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCB-1.png"}}, "nickname": "cbillington", "type": "user", "account_id": "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2014-10-03T23:51:09.847961+00:00", "milestone": null, "updated_on": "2014-10-04T08:53:06.716507+00:00", "type": "issue", "id": 29}