{"pagelen": 100, "values": [{"changes": {"state": {"new": "resolved", "old": "new"}}, "links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/2/changes/17102726.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/2#comment-17102726"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer/issues/2.json"}}, "type": "issue", "id": 2, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "title": "PyQtGraph v0.9.10 is incompatible with runviewer 2.0.1"}, "created_on": "2015-04-02T05:26:15.455171+00:00", "user": {"display_name": "Philip Starkey", "uuid": "{48af65db-e5fc-459c-a7eb-52eb1f9a5690}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D"}, "html": {"href": "https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/dc318537facc47ebe1ae98a7aabacecfd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPS-0.png"}}, "nickname": "pstarkey", "type": "user", "account_id": "557058:52a111e4-40da-4441-9143-417f95f2db97"}, "message": {"raw": "Resolved in changeset d6a4996", "markup": "markdown", "html": "<p>Resolved in changeset <a href=\"#!/labscript_suite/runviewer/commits/d6a4996\" rel=\"nofollow\" class=\"ap-connect-link\">d6a4996</a></p>", "type": "rendered"}, "type": "issue_change", "id": 17102726}], "page": 1, "size": 1}